### ISSUE TITLE
Navbar improvements

### ISSUE THREAD

**Issue by Nicolas-Gth** [loof2736/scyfin#26]
1. The h3 heading has margin even when it's empty, which creates this ugly space :
![image](https://github.com/user-attachments/assets/7f92b8cf-bcfd-4e14-97d9-c29281743705)

2. The right and left headers are unaligned due to uneven margin spaces :
![image](https://github.com/user-attachments/assets/0e550da5-3272-4cac-a289-267ba538812d)

This is my fix:
```css
@media (max-width: 1599px) {
  .layout-desktop .headerLeft:not(.libraryDocument:has(.videoPlayerContainer) .headerLeft) {
   margin-bottom: 10px !important;
   margin-left: 15px !important;
 }
}

.layout-desktop .headerLeft:not(.libraryDocument:has(.videoPlayerContainer) .headerLeft) {
  margin-bottom: 10px !important;
}
```
