### ISSUE TITLE
Intro Skipper plugin compatibility problem

### ISSUE THREAD

**Issue by Slinet6056** [loof2736/scyfin#27]
The current theme seems to have some styling issues with the "Skip Intro" button from the Intro Skipper plugin:

![PixPin_2024-07-23_18-30-00](https://github.com/user-attachments/assets/0a1ac96d-b050-4174-a73d-210c3f1126c2) ![PixPin_2024-07-23_18-30-50](https://github.com/user-attachments/assets/e2fa8da4-a81d-484a-90cf-57ba24d5f6ab)

Here's my fix:

```css
#skipIntro {
    &.upNextContainer {
        background-color: transparent !important;
        backdrop-filter: none !important;
    }
    .emby-button {
        border-radius: var(--rounded-cards) !important;
        background-color: rgba(0, 0, 0, 0.7) !important;
        &:hover, &:focus {
            background-color: rgba(var(--accent), 0.7) !important;
        }
    }
}
```

Now the "Skip Intro" button looks like this:

![PixPin_2024-07-23_18-31-16](https://github.com/user-attachments/assets/21976007-5840-4115-a759-47dffd11938a) ![PixPin_2024-07-23_18-31-32](https://github.com/user-attachments/assets/ab82d629-b2e4-4208-a43b-6c57d58effa5)

Since the Intro Skipper plugin is not used by everyone, perhaps a separate CSS file could be considered for users who want to use both the theme and the Intro Skipper plugin.
