### ISSUE TITLE
A few enhancements and fixes

### ISSUE THREAD

**Issue by M4TH1EU** [loof2736/scyfin#32]
Hi, 

First of all, thanks for the great theme. After experimenting with it, I found a few small fixes that could be merged into the theme.

_I've seen in one of the PR that you are not really comfortable with using github PR so I though I would just report them back here to make it easier._

1. When using a color theme such a coral some texts and icons still have the Jellyfin blue color, fixed with this : 
```css
/* Fix hover color on texts/buttons */
.listItemImageButton:hover {
    color: var(--primary-accent-color) !important;
}
.button-flat:hover {
    color: var(--primary-accent-color) !important;
}
```

2. The progress bar and the progress text also stay blue, fix :
```css
/* Fix for progress bar colo^ (admin) */
progress::-moz-progress-bar,
progress::-webkit-progress-value,
progress[aria-valuenow]:before {
    background-color: var(--primary-accent-color) !important;
}

/* Fix progress bar (admin) text color */
#divRunningTasks span {
    color: var(--primary-accent-color) !important;
}
```

3. The clients cards on the admin page also have 5 shades of blue that don't change when using color theme. This one requires a bit more code, I though of two approaches, either we define 5 static shades of the primary accent into the color.css file or we dynamically calculate the accents but this requires a lot of code (see spoiler), I'll let you choose the one you prefer : 
<details>
  <summary>Code</summary>
  
```css
:root {
    --theme-accent-r: 234;
    --theme-accent-g: 112;
    --theme-accent-b: 112;

    --primary-accent-color: rgb(var(--theme-accent-r), var(--theme-accent-g), var(--theme-accent-b));
    --secondary-accent-color: rgb(var(--theme-accent-r), var(--theme-accent-g), var(--theme-accent-b), 0.2);

    --accent-shade-1: rgb(calc(var(--theme-accent-r) - 30), calc(var(--theme-accent-g) - 30), calc(var(--theme-accent-b) - 30), 1);
    --accent-shade-2: rgb(calc(var(--theme-accent-r) - 30), calc(var(--theme-accent-g) - 30), calc(var(--theme-accent-b) - 30), 0.9);
    --accent-shade-3: rgb(calc(var(--theme-accent-r) - 30), calc(var(--theme-accent-g) - 30), calc(var(--theme-accent-b) - 30), 0.8);
    --accent-shade-4: rgb(calc(var(--theme-accent-r) - 30), calc(var(--theme-accent-g) - 30), calc(var(--theme-accent-b) - 30), 0.7);
    --accent-shade-5: rgb(calc(var(--theme-accent-r) - 30), calc(var(--theme-accent-g) - 30), calc(var(--theme-accent-b) - 30), 0.6);
}
```
  
</details>

```css
/* Custom red colors on Active Devices in Admin Homepage */
.defaultCardBackground1 {
    background-color: var(--accent-shade-1) !important;
}

.defaultCardBackground2 {
    background-color: var(--accent-shade-2) !important;
}

.defaultCardBackground3 {
    background-color: var(--accent-shade-3) !important;
}

.defaultCardBackground4 {
    background-color: var(--accent-shade-4) !important;
}

.defaultCardBackground5 {
    background-color: var(--accent-shade-5) !important;
}
```

And that's it :)
