### ISSUE TITLE
Intro skipper button suggestions

### ISSUE THREAD

**Issue by Nicolas-Gth** [loof2736/scyfin#37]
This is more of a suggestion than an issue. I think the skip intro button would look more coherent if it was rounded like the navbar. Also, I'm using the white theme and the fact that it goes blue on hover, even thought everything is white, bothers me a little, so I made these edits.
And finally, wouldn't it be better if the button was on hover like the rest of the player controls (I don't really know how to do that) ?

![image](https://github.com/user-attachments/assets/a3407ece-8bfd-4a3b-9266-6cd445f2e25a)
![image](https://github.com/user-attachments/assets/50c695c1-bbb4-4cbf-946b-5226bd5754f5)

```CSS
#skipIntro {
    &.upNextContainer {
        background-color: transparent !important;
        backdrop-filter: none !important;
    }
    .emby-button {
        border-radius:100px !important;
        background-color: rgba(0, 0, 0, 0.7) !important;
        &:hover, &:focus {
            background-color: rgba(151, 151, 151, 0.7) !important;
        }
    }
}
#skipIntro .emby-button:hover {
                background: rgb(var(--accent));
                box-shadow: 0 0 8px rgba(151, 151, 151, 0.6);
                filter: brightness(1.2);
}
#skipIntro .emby-button:focus {
                background: rgb(var(--accent));
                box-shadow: 0 0 8px rgba(151, 151, 151, 0.6);
}
```
