### ISSUE TITLE
Snow theme player slider wrong color on Chrome

### ISSUE THREAD

**Issue by Nicolas-Gth** [loof2736/scyfin#38]
It seems that you forgot to replace the colors in the playback-video.css file.
![image](https://github.com/user-attachments/assets/f1baabbd-5d30-479e-b085-fb28b138c7c9)

My fix for chrome (but the shape is still not the same as Firefox and I would be better to use the --accent variable rather than hardcoding the color hex).
```CSS
.mdl-slider::-webkit-slider-thumb {
              background: #fff;
}
```
![image](https://github.com/user-attachments/assets/1b1a1525-5353-4014-aab8-f487effde8f5)

I saw many other classes with the hard coded blue color that I think should be replaced with the --accent variable
```CSS
.countIndicator, .fullSyncIndicator, .mediaSourceIndicator, .playedIndicator {
    background: #fff;
}
```
for example
