### ISSUE TITLE
Avoid list items crop

### ISSUE THREAD

**Issue by Julien9969** [loof2736/scyfin#40]
Could be great to set background-size to **contain** insted of **cover** to make cover not croped

```css
.listItemImage {
    background-size: cover;
    ...
}
```
![image](https://github.com/user-attachments/assets/8923fe6d-a2cf-4523-9636-bb3868b610cb)

```css
.listItemImage {
    background-size: contain;
    ...
}
```
![image](https://github.com/user-attachments/assets/4ab7d259-baf2-4d2e-88a8-af12d4c01e01)
