### ISSUE TITLE
Better-fitting fast-rewind and fast-forward icons

### ISSUE THREAD

**Issue by Nicolas-Gth** [loof2736/scyfin#43]
![{2ED73BE7-56BB-4A79-B701-AA000032E3AD}](https://github.com/user-attachments/assets/8c3f6acd-981e-4bb4-866a-aa60c50f0cfd)

```CSS
.material-icons.fast_rewind::before {
  content: "\e059";
}
.material-icons.fast_forward::before {
  content: "\e057";
}
```
I think these are more suited than a double arrow, which is more of a constant forward/rewind indicator rather than a one tap -10s or +30s.

**Comment by Nicolas-Gth** [comment]
same thing for the audio track :
![{FECD4B72-4D00-491B-ADE8-F8F6C3C70D98}](https://github.com/user-attachments/assets/7546ae86-6561-4dc3-a929-881962ade1e5)


```CSS
.material-icons.audiotrack::before {
  content: "\e91f";
}
```
