### ISSUE TITLE
Player broken after update 10.10.0

### ISSUE THREAD

**Issue by Julien9969** [loof2736/scyfin#44]
All player elements are stack on the left after update

![image](https://github.com/user-attachments/assets/c717bd36-17ad-4498-8e84-fca611487010)

![image](https://github.com/user-attachments/assets/7b79347f-b36b-4137-be5e-3845747cf878)

can be fix by adding 
```css
.osdTimeText {
    margin-right: 1em;
    margin-left: auto; /* this make everything except play pause container to the right */
}
```
